# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dex_control.proto import franka_pb2 as franka__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in franka_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrankaRobotStub(object):
    """Generic RPC service for Franka robot control.
    Uses repeated doubles for flexible vector arguments (joints, poses, etc.).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJointPositions = channel.unary_unary(
                '/franka.FrankaRobot/GetJointPositions',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.JointValues.FromString,
                _registered_method=True)
        self.GetEePose = channel.unary_unary(
                '/franka.FrankaRobot/GetEePose',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.EePose.FromString,
                _registered_method=True)
        self.GetExternalTorques = channel.unary_unary(
                '/franka.FrankaRobot/GetExternalTorques',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.JointValues.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/franka.FrankaRobot/GetState',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.RobotState.FromString,
                _registered_method=True)
        self.MoveEePose = channel.unary_unary(
                '/franka.FrankaRobot/MoveEePose',
                request_serializer=franka__pb2.MoveEePoseRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.MoveEeWaypoints = channel.unary_unary(
                '/franka.FrankaRobot/MoveEeWaypoints',
                request_serializer=franka__pb2.WaypointsRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.MoveJoints = channel.unary_unary(
                '/franka.FrankaRobot/MoveJoints',
                request_serializer=franka__pb2.MoveJointsRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.MoveJointWaypoints = channel.unary_unary(
                '/franka.FrankaRobot/MoveJointWaypoints',
                request_serializer=franka__pb2.WaypointsRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GetGripperWidth = channel.unary_unary(
                '/franka.FrankaRobot/GetGripperWidth',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.FloatResponse.FromString,
                _registered_method=True)
        self.GetGripperMaxWidth = channel.unary_unary(
                '/franka.FrankaRobot/GetGripperMaxWidth',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.FloatResponse.FromString,
                _registered_method=True)
        self.IsGripperGrasped = channel.unary_unary(
                '/franka.FrankaRobot/IsGripperGrasped',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.MoveGripper = channel.unary_unary(
                '/franka.FrankaRobot/MoveGripper',
                request_serializer=franka__pb2.MoveGripperRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.OpenGripper = channel.unary_unary(
                '/franka.FrankaRobot/OpenGripper',
                request_serializer=franka__pb2.GripperActionRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GraspObject = channel.unary_unary(
                '/franka.FrankaRobot/GraspObject',
                request_serializer=franka__pb2.GraspRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.StopGripper = channel.unary_unary(
                '/franka.FrankaRobot/StopGripper',
                request_serializer=franka__pb2.GripperActionRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.HomingGripper = channel.unary_unary(
                '/franka.FrankaRobot/HomingGripper',
                request_serializer=franka__pb2.GripperActionRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.SetJointImpedance = channel.unary_unary(
                '/franka.FrankaRobot/SetJointImpedance',
                request_serializer=franka__pb2.JointValues.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.StartGravityCompensation = channel.unary_unary(
                '/franka.FrankaRobot/StartGravityCompensation',
                request_serializer=franka__pb2.DurationRequest.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.StopMotion = channel.unary_unary(
                '/franka.FrankaRobot/StopMotion',
                request_serializer=franka__pb2.Empty.SerializeToString,
                response_deserializer=franka__pb2.BoolResponse.FromString,
                _registered_method=True)


class FrankaRobotServicer(object):
    """Generic RPC service for Franka robot control.
    Uses repeated doubles for flexible vector arguments (joints, poses, etc.).

    """

    def GetJointPositions(self, request, context):
        """State queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEePose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExternalTorques(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveEePose(self, request, context):
        """Motion commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveEeWaypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJointWaypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGripperWidth(self, request, context):
        """Gripper state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGripperMaxWidth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsGripperGrasped(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveGripper(self, request, context):
        """Gripper control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraspObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HomingGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointImpedance(self, request, context):
        """Impedance / kinesthetic teaching
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGravityCompensation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrankaRobotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointPositions,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.JointValues.SerializeToString,
            ),
            'GetEePose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEePose,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.EePose.SerializeToString,
            ),
            'GetExternalTorques': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExternalTorques,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.JointValues.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.RobotState.SerializeToString,
            ),
            'MoveEePose': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveEePose,
                    request_deserializer=franka__pb2.MoveEePoseRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'MoveEeWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveEeWaypoints,
                    request_deserializer=franka__pb2.WaypointsRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'MoveJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJoints,
                    request_deserializer=franka__pb2.MoveJointsRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'MoveJointWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJointWaypoints,
                    request_deserializer=franka__pb2.WaypointsRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'GetGripperWidth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGripperWidth,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.FloatResponse.SerializeToString,
            ),
            'GetGripperMaxWidth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGripperMaxWidth,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.FloatResponse.SerializeToString,
            ),
            'IsGripperGrasped': grpc.unary_unary_rpc_method_handler(
                    servicer.IsGripperGrasped,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'MoveGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveGripper,
                    request_deserializer=franka__pb2.MoveGripperRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'OpenGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenGripper,
                    request_deserializer=franka__pb2.GripperActionRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'GraspObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GraspObject,
                    request_deserializer=franka__pb2.GraspRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'StopGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.StopGripper,
                    request_deserializer=franka__pb2.GripperActionRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'HomingGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.HomingGripper,
                    request_deserializer=franka__pb2.GripperActionRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'SetJointImpedance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointImpedance,
                    request_deserializer=franka__pb2.JointValues.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'StartGravityCompensation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGravityCompensation,
                    request_deserializer=franka__pb2.DurationRequest.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
            'StopMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMotion,
                    request_deserializer=franka__pb2.Empty.FromString,
                    response_serializer=franka__pb2.BoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'franka.FrankaRobot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('franka.FrankaRobot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrankaRobot(object):
    """Generic RPC service for Franka robot control.
    Uses repeated doubles for flexible vector arguments (joints, poses, etc.).

    """

    @staticmethod
    def GetJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetJointPositions',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.JointValues.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEePose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetEePose',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.EePose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExternalTorques(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetExternalTorques',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.JointValues.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetState',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveEePose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/MoveEePose',
            franka__pb2.MoveEePoseRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveEeWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/MoveEeWaypoints',
            franka__pb2.WaypointsRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/MoveJoints',
            franka__pb2.MoveJointsRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveJointWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/MoveJointWaypoints',
            franka__pb2.WaypointsRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGripperWidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetGripperWidth',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.FloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGripperMaxWidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GetGripperMaxWidth',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.FloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsGripperGrasped(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/IsGripperGrasped',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/MoveGripper',
            franka__pb2.MoveGripperRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/OpenGripper',
            franka__pb2.GripperActionRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraspObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/GraspObject',
            franka__pb2.GraspRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/StopGripper',
            franka__pb2.GripperActionRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HomingGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/HomingGripper',
            franka__pb2.GripperActionRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointImpedance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/SetJointImpedance',
            franka__pb2.JointValues.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGravityCompensation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/StartGravityCompensation',
            franka__pb2.DurationRequest.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka.FrankaRobot/StopMotion',
            franka__pb2.Empty.SerializeToString,
            franka__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
